//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicios_Vehiculos_ITM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agencia
    {
        public int Id_Agencia { get; set; }
        public string Nombre { get; set; }
        public string Ubicacion { get; set; }
    }
}
